# use default ruff config, add to pyproject.toml if needed
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.2
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0  # Use the ref you want to point at
  hooks:
    - id: requirements-txt-fixer
    - id: pretty-format-json
      args: [--autofix]
    - id: check-illegal-windows-names
    